import { Pencil, Plus, Trash2 } from 'lucide-react';
import { Button } from '@/components/ui/button';
import type { RoomAssignment } from '../roomModel';
import { RoomTable, roomRowClass } from './RoomTable';

type RoomGroup = { roomNumber: string; assignments: RoomAssignment[]; assignmentCount: number; classCount: number };
type Props = { rooms: RoomGroup[]; selected: string; onSelect: (room: string) => void; onAssign: () => void; onEdit: (row: RoomAssignment) => void; onDeleteAssignment: (id: number) => void; onDeleteRoom: () => void };
export const RoomInventory = ({ rooms, selected, onSelect, onAssign, onEdit, onDeleteAssignment, onDeleteRoom }: Props) => {
  const room = rooms.find((item) => item.roomNumber === selected) || rooms[0];
  return <section className="border-t p-3" data-testid="room-inventory"><div className="mb-3 flex flex-col gap-2 sm:flex-row sm:items-center sm:justify-between"><div><h2 className="text-sm font-bold">Rooms & recurring assignments</h2><p className="text-xs text-muted-foreground">Manage the physical room list and weekly schedules.</p></div><div className="flex gap-2"><Button size="sm" variant="outline" onClick={onAssign} disabled={!room}><Plus className="mr-1 h-4 w-4" />Assign class</Button><Button size="sm" variant="destructive" onClick={onDeleteRoom} disabled={!room}><Trash2 className="mr-1 h-4 w-4" />Delete room</Button></div></div>
  <div className="mb-3 flex gap-2 overflow-x-auto">{rooms.map((item) => <button type="button" key={item.roomNumber} onClick={() => onSelect(item.roomNumber)} className={`min-w-32 rounded-lg border px-3 py-2 text-left text-xs ${item.roomNumber === room?.roomNumber ? 'border-primary bg-primary/10 text-primary' : 'bg-card hover:bg-muted'}`}><span className="block font-bold">{item.roomNumber}</span><span className="text-muted-foreground">{item.classCount} classes · {item.assignmentCount} slots</span></button>)}</div>
  {room && <RoomTable label={`Assignments for ${room.roomNumber}`} headers={['Group', 'Day', 'Time', 'Actions']}>{room.assignments.map((assignment) => <tr key={assignment.room_id} className={roomRowClass}><td className="px-3 py-2 font-semibold">{assignment.class_name || `Group #${assignment.class_id}`}</td><td className="px-3 py-2">{assignment.day}</td><td className="px-3 py-2 font-mono">{String(assignment.time || '').slice(0, 5)}–{String(assignment.end_time || '').slice(0, 5)}</td><td className="px-3 py-2"><Button size="icon" variant="ghost" aria-label={`Edit assignment ${assignment.room_id}`} onClick={() => onEdit(assignment)}><Pencil className="h-4 w-4" /></Button><Button size="icon" variant="ghost" className="text-destructive" aria-label={`Delete assignment ${assignment.room_id}`} onClick={() => onDeleteAssignment(assignment.room_id)}><Trash2 className="h-4 w-4" /></Button></td></tr>)}</RoomTable>}
  {!room && <div className="rounded-lg border border-dashed p-8 text-center text-sm text-muted-foreground">No rooms yet. Create the first room to start scheduling.</div>}</section>;
};
