const {
  bigint,
  boolean,
  date,
  integer,
  jsonb,
  numeric,
  pgTable,
  serial,
  text,
  time,
  timestamp,
  varchar,
} = require('drizzle-orm/pg-core');

const appSettings = pgTable('app_settings', {
  settingId: serial('setting_id').primaryKey(),
  centerId: integer('center_id'),
  settingKey: varchar('setting_key', { length: 100 }).notNull(),
  settingValue: jsonb('setting_value').notNull(),
  createdAt: timestamp('created_at'),
  updatedAt: timestamp('updated_at'),
});

const translations = pgTable('translations', {
  id: text('id').primaryKey(),
  english: text('english').notNull(),
  uzbek: text('uzbek').notNull(),
});

const savedFilters = pgTable('saved_filters', {
  filterId: serial('filter_id').primaryKey(),
  centerId: integer('center_id'),
  userType: varchar('user_type', { length: 20 }).notNull(),
  userId: integer('user_id').notNull(),
  name: varchar('name', { length: 100 }).notNull(),
  entity: varchar('entity', { length: 50 }).notNull(),
  filtersJson: jsonb('filters_json').notNull(),
  createdAt: timestamp('created_at'),
  updatedAt: timestamp('updated_at'),
});

const teacherTasks = pgTable('teacher_tasks', {
  taskId: serial('task_id').primaryKey(),
  centerId: integer('center_id'),
  teacherId: integer('teacher_id'),
  adminId: integer('admin_id'),
  assigneeType: varchar('assignee_type', { length: 20 }).notNull(),
  createdBy: integer('created_by'),
  taskTitle: varchar('task_title', { length: 255 }).notNull(),
  taskDefinition: text('task_definition'),
  deadline: timestamp('deadline'),
  status: varchar('status', { length: 20 }).notNull(),
  statusNote: text('status_note'),
  createdAt: timestamp('created_at'),
  updatedAt: timestamp('updated_at'),
});

const teacherSalaries = pgTable('teacher_salaries', {
  salaryId: serial('salary_id').primaryKey(),
  centerId: integer('center_id'),
  teacherId: integer('teacher_id').notNull(),
  salaryYear: integer('salary_year').notNull(),
  salaryMonth: integer('salary_month').notNull(),
  amount: numeric('amount').notNull(),
  isPaid: boolean('is_paid').notNull(),
  paidAt: timestamp('paid_at'),
  markedById: integer('marked_by_id'),
  markedByUserType: varchar('marked_by_user_type', { length: 20 }),
  markedByRole: varchar('marked_by_role', { length: 50 }),
  markedByName: varchar('marked_by_name', { length: 200 }),
  paymentMethod: varchar('payment_method', { length: 50 }),
  notes: text('notes'),
  createdAt: timestamp('created_at'),
  updatedAt: timestamp('updated_at'),
});

const teacherKpis = pgTable('teacher_kpis', {
  kpiId: serial('kpi_id').primaryKey(),
  centerId: integer('center_id'),
  teacherId: integer('teacher_id').notNull(),
  kpiYear: integer('kpi_year').notNull(),
  kpiMonth: integer('kpi_month').notNull(),
  studentScore: numeric('student_score').notNull(),
  retentionScore: numeric('retention_score').notNull(),
  contributionScore: numeric('contribution_score').notNull(),
  teachingQualityScore: numeric('teaching_quality_score').notNull(),
  finalScore: numeric('final_score').notNull(),
  notes: text('notes'),
  markedById: integer('marked_by_id'),
  markedByUserType: varchar('marked_by_user_type', { length: 20 }),
  markedByRole: varchar('marked_by_role', { length: 50 }),
  markedByName: varchar('marked_by_name', { length: 200 }),
  createdAt: timestamp('created_at'),
  updatedAt: timestamp('updated_at'),
});

const notifications = pgTable('notifications', {
  notificationId: serial('notification_id').primaryKey(),
  centerId: integer('center_id'),
  userType: varchar('user_type', { length: 20 }).notNull(),
  userId: integer('user_id').notNull(),
  title: varchar('title', { length: 200 }).notNull(),
  message: text('message').notNull(),
  type: varchar('type', { length: 20 }),
  isRead: boolean('is_read'),
  createdAt: timestamp('created_at'),
});

const teacherPaymentCredentials = pgTable('teacher_payment_credentials', {
  teacherId: integer('teacher_id').primaryKey(),
  passwordHash: varchar('password_hash', { length: 255 }).notNull(),
  isActive: boolean('is_active'),
  createdBy: integer('created_by'),
  updatedBy: integer('updated_by'),
  createdAt: timestamp('created_at'),
  updatedAt: timestamp('updated_at'),
  lastUsedAt: timestamp('last_used_at'),
});

const centers = pgTable('edu_centers', {
  centerId: serial('center_id').primaryKey(),
  centerName: varchar('center_name', { length: 255 }),
  centerCode: varchar('center_code', { length: 100 }),
  email: varchar('email', { length: 255 }),
  phone: varchar('phone', { length: 50 }),
  address: text('address'),
  city: varchar('city', { length: 100 }),
  principalName: varchar('principal_name', { length: 255 }),
  createdAt: timestamp('created_at'),
  updatedAt: timestamp('updated_at'),
});

const rooms = pgTable('rooms', {
  roomId: serial('room_id').primaryKey(),
  centerId: integer('center_id').notNull(),
  roomNumber: varchar('room_number', { length: 50 }).notNull(),
  physicalRoomId: integer('physical_room_id'),
  classId: integer('class_id'),
  day: varchar('day', { length: 20 }),
  time: time('time'),
  endTime: time('end_time'),
  createdAt: timestamp('created_at'),
  updatedAt: timestamp('updated_at'),
});

const physicalRooms = pgTable('physical_rooms', {
  physicalRoomId: serial('physical_room_id').primaryKey(),
  centerId: integer('center_id').notNull(),
  name: varchar('name', { length: 50 }).notNull(),
  capacity: integer('capacity'),
  location: varchar('location', { length: 255 }),
  status: varchar('status', { length: 30 }).notNull(),
  features: jsonb('features'),
  operatingStartTime: time('operating_start_time').notNull(),
  operatingEndTime: time('operating_end_time').notNull(),
  createdAt: timestamp('created_at'),
  updatedAt: timestamp('updated_at'),
});

const classes = pgTable('classes', {
  classId: serial('class_id').primaryKey(),
  centerId: integer('center_id').notNull(),
  className: varchar('class_name', { length: 100 }).notNull(),
  classCode: varchar('class_code', { length: 50 }).notNull(),
  level: integer('level'),
  section: text('section'),
  capacity: integer('capacity'),
  teacherId: integer('teacher_id'),
  roomNumber: varchar('room_number', { length: 50 }),
  totalStudents: integer('total_students'),
  paymentAmount: numeric('payment_amount'),
  paymentFrequency: varchar('payment_frequency', { length: 20 }),
  startDate: timestamp('start_date'),
  endDate: timestamp('end_date'),
  deletedAt: timestamp('deleted_at'),
  createdAt: timestamp('created_at'),
  updatedAt: timestamp('updated_at'),
});

const teachers = pgTable('teachers', {
  teacherId: serial('teacher_id').primaryKey(),
  centerId: integer('center_id'),
  firstName: varchar('first_name', { length: 100 }),
  lastName: varchar('last_name', { length: 100 }),
  employeeId: varchar('employee_id', { length: 100 }),
  username: varchar('username', { length: 100 }),
  passwordHash: varchar('password_hash', { length: 255 }),
  email: varchar('email', { length: 255 }),
  phone: varchar('phone', { length: 50 }),
  dateOfBirth: date('date_of_birth'),
  gender: varchar('gender', { length: 20 }),
  qualification: varchar('qualification', { length: 255 }),
  specialization: varchar('specialization', { length: 100 }),
  salaryPercentage: numeric('salary_percentage'),
  status: varchar('status', { length: 50 }),
  roles: jsonb('roles'),
  deletedAt: timestamp('deleted_at'),
  createdAt: timestamp('created_at'),
  updatedAt: timestamp('updated_at'),
});

const studentAcquisitionSources = pgTable('student_acquisition_sources', {
  sourceId: serial('source_id').primaryKey(),
  sourceCode: varchar('source_code', { length: 50 }).notNull(),
  sourceName: varchar('source_name', { length: 100 }).notNull(),
  active: boolean('active'),
  createdAt: timestamp('created_at'),
});

const studentActionReasons = pgTable('student_action_reasons', {
  reasonId: serial('reason_id').primaryKey(),
  reasonType: varchar('reason_type', { length: 20 }).notNull(),
  reasonCode: varchar('reason_code', { length: 50 }).notNull(),
  reasonName: varchar('reason_name', { length: 100 }).notNull(),
  active: boolean('active'),
  createdAt: timestamp('created_at'),
});

const students = pgTable('students', {
  studentId: serial('student_id').primaryKey(),
  centerId: integer('center_id'),
  enrollmentNumber: varchar('enrollment_number', { length: 100 }),
  firstName: varchar('first_name', { length: 255 }),
  lastName: varchar('last_name', { length: 255 }),
  username: varchar('username', { length: 100 }),
  passwordHash: varchar('password_hash', { length: 255 }),
  email: varchar('email', { length: 255 }),
  phone: varchar('phone', { length: 50 }),
  dateOfBirth: date('date_of_birth'),
  parentName: varchar('parent_name', { length: 255 }),
  parentPhone: varchar('parent_phone', { length: 50 }),
  gender: varchar('gender', { length: 20 }),
  status: varchar('status', { length: 50 }),
  teacherId: integer('teacher_id'),
  classId: integer('class_id'),
  previousClassId: integer('previous_class_id'),
  schoolName: varchar('school_name', { length: 255 }),
  schoolClass: varchar('school_class', { length: 50 }),
  isFrozen: boolean('is_frozen'),
  coins: integer('coins'),
  acquisitionSourceId: integer('acquisition_source_id'),
  acquisitionDetail: text('acquisition_detail'),
  referredByTeacherId: integer('referred_by_teacher_id'),
  transferReasonId: integer('transfer_reason_id'),
  deleteReasonId: integer('delete_reason_id'),
  deletedAt: timestamp('deleted_at'),
  createdAt: timestamp('created_at'),
  updatedAt: timestamp('updated_at'),
});

const roomSlots = pgTable('room_slots', {
  slotId: serial('slot_id').primaryKey(),
  centerId: integer('center_id').notNull(),
  roomId: integer('room_id').notNull(),
  slotDate: date('slot_date'),
  startTime: time('start_time'),
  endTime: time('end_time'),
  durationMinutes: integer('duration_minutes'),
  isAvailable: boolean('is_available'),
  createdAt: timestamp('created_at'),
  updatedAt: timestamp('updated_at'),
});

const roomBookings = pgTable('room_bookings', {
  bookingId: serial('booking_id').primaryKey(),
  centerId: integer('center_id').notNull(),
  slotId: integer('slot_id').notNull(),
  classId: integer('class_id').notNull(),
  sessionId: integer('session_id'),
  teacherId: integer('teacher_id'),
  bookingDate: timestamp('booking_date'),
  bookingStatus: varchar('booking_status', { length: 50 }),
  notes: text('notes'),
  createdAt: timestamp('created_at'),
  updatedAt: timestamp('updated_at'),
});

const assignments = pgTable('assignments', {
  assignmentId: serial('assignment_id').primaryKey(),
  centerId: integer('center_id'),
  classId: integer('class_id'),
  subjectId: integer('subject_id'),
  teacherId: integer('teacher_id'),
  assignmentTitle: varchar('assignment_title', { length: 255 }),
  title: varchar('title', { length: 255 }),
  description: text('description'),
  dueDate: timestamp('due_date'),
  submissionDate: timestamp('submission_date'),
  status: varchar('status', { length: 50 }),
  grade: numeric('grade'),
  studentId: integer('student_id'),
  deletedAt: timestamp('deleted_at'),
  createdAt: timestamp('created_at'),
  updatedAt: timestamp('updated_at'),
});

const attendance = pgTable('attendance', {
  attendanceId: serial('attendance_id').primaryKey(),
  centerId: integer('center_id'),
  studentId: integer('student_id'),
  classId: integer('class_id'),
  sessionId: integer('session_id'),
  teacherId: integer('teacher_id'),
  attendanceDate: date('attendance_date'),
  status: varchar('status', { length: 50 }),
  notes: text('notes'),
  remarks: text('remarks'),
  createdAt: timestamp('created_at'),
});

const auditLogs = pgTable('audit_logs', {
  auditLogId: serial('audit_log_id').primaryKey(),
  centerId: integer('center_id'),
  userType: varchar('user_type', { length: 50 }),
  userId: integer('user_id'),
  action: varchar('action', { length: 100 }),
  entityType: varchar('entity_type', { length: 100 }),
  entityId: integer('entity_id'),
  details: jsonb('details'),
  ipAddress: varchar('ip_address', { length: 100 }),
  createdAt: timestamp('created_at'),
});

const debts = pgTable('debts', {
  debtId: serial('debt_id').primaryKey(),
  centerId: integer('center_id'),
  studentId: integer('student_id'),
  debtAmount: numeric('debt_amount'),
  debtDate: date('debt_date'),
  amountPaid: numeric('amount_paid'),
  amount: numeric('amount'),
  paidAmount: numeric('paid_amount'),
  balance: numeric('balance'),
  status: varchar('status', { length: 50 }),
  remarks: text('remarks'),
  dueDate: date('due_date'),
  deletedAt: timestamp('deleted_at'),
  createdAt: timestamp('created_at'),
  updatedAt: timestamp('updated_at'),
});

const discounts = pgTable('discounts', {
  discountId: serial('discount_id').primaryKey(),
  studentId: integer('student_id'),
  centerId: integer('center_id'),
  discountType: varchar('discount_type', { length: 20 }),
  discountKind: varchar('discount_kind', { length: 40 }),
  value: numeric('value'),
  originalPrice: numeric('original_price'),
  finalPrice: numeric('final_price'),
  reason: text('reason'),
  paymentPeriod: varchar('payment_period', { length: 20 }),
  startDate: date('start_date'),
  endDate: date('end_date'),
  active: boolean('active'),
  createdAt: timestamp('created_at'),
  updatedAt: timestamp('updated_at'),
});

const grades = pgTable('grades', {
  gradeId: serial('grade_id').primaryKey(),
  centerId: integer('center_id'),
  studentId: integer('student_id'),
  classId: integer('class_id'),
  subjectId: integer('subject_id'),
  sessionId: integer('session_id'),
  teacherId: integer('teacher_id'),
  subject: varchar('subject', { length: 255 }),
  marksObtained: numeric('marks_obtained'),
  totalMarks: numeric('total_marks'),
  percentage: numeric('percentage'),
  gradeLetter: varchar('grade_letter', { length: 10 }),
  academicYear: varchar('academic_year', { length: 20 }),
  term: varchar('term', { length: 50 }),
  score: numeric('score'),
  gradeType: varchar('grade_type', { length: 50 }),
  attendanceScore: numeric('attendance_score'),
  homeworkScore: numeric('homework_score'),
  activityScore: numeric('activity_score'),
  pointsScore: numeric('points_score'),
  baseCoin: integer('base_coin'),
  totalDailyCoin: integer('total_daily_coin'),
  coinComment: text('coin_comment'),
  notes: text('notes'),
  createdAt: timestamp('created_at'),
  updatedAt: timestamp('updated_at'),
});

const importJobs = pgTable('import_jobs', {
  importJobId: serial('import_job_id').primaryKey(),
  centerId: integer('center_id'),
  entity: varchar('entity', { length: 100 }),
  status: varchar('status', { length: 50 }),
  details: jsonb('details'),
  createdAt: timestamp('created_at'),
  updatedAt: timestamp('updated_at'),
});

const invoices = pgTable('invoices', {
  invoiceId: serial('invoice_id').primaryKey(),
  centerId: integer('center_id'),
  studentId: integer('student_id'),
  invoiceNumber: varchar('invoice_number', { length: 100 }),
  status: varchar('status', { length: 50 }),
  subtotal: numeric('subtotal'),
  discountTotal: numeric('discount_total'),
  taxTotal: numeric('tax_total'),
  total: numeric('total'),
  totalAmount: numeric('total_amount'),
  notes: text('notes'),
  issueDate: date('issue_date'),
  dueDate: date('due_date'),
  createdAt: timestamp('created_at'),
  updatedAt: timestamp('updated_at'),
});

const invoiceItems = pgTable('invoice_items', {
  itemId: serial('item_id').primaryKey(),
  invoiceId: integer('invoice_id'),
  description: text('description'),
  quantity: numeric('quantity'),
  unitPrice: numeric('unit_price'),
  total: numeric('total'),
  createdAt: timestamp('created_at'),
  updatedAt: timestamp('updated_at'),
});

const owners = pgTable('owners', {
  ownerId: serial('owner_id').primaryKey(),
  username: varchar('username', { length: 100 }),
  passwordHash: varchar('password_hash', { length: 255 }),
  firstName: varchar('first_name', { length: 100 }),
  lastName: varchar('last_name', { length: 100 }),
  email: varchar('email', { length: 255 }),
  status: varchar('status', { length: 50 }),
  isLocked: boolean('is_locked'),
  loginAttempts: integer('login_attempts'),
  canHardDelete: boolean('can_hard_delete'),
  lastLogin: timestamp('last_login'),
  createdAt: timestamp('created_at'),
  updatedAt: timestamp('updated_at'),
});

const parents = pgTable('parents', {
  parentId: serial('parent_id').primaryKey(),
  centerId: integer('center_id'),
  username: varchar('username', { length: 100 }),
  passwordHash: varchar('password_hash', { length: 255 }),
  firstName: varchar('first_name', { length: 100 }),
  lastName: varchar('last_name', { length: 100 }),
  email: varchar('email', { length: 255 }),
  phone: varchar('phone', { length: 50 }),
  status: varchar('status', { length: 50 }),
  createdAt: timestamp('created_at'),
  updatedAt: timestamp('updated_at'),
});

const parentStudents = pgTable('parent_students', {
  parentId: integer('parent_id'),
  studentId: integer('student_id'),
  relationship: varchar('relationship', { length: 100 }),
  isPrimary: boolean('is_primary'),
  createdAt: timestamp('created_at'),
  updatedAt: timestamp('updated_at'),
});

const paymentPlans = pgTable('payment_plans', {
  planId: serial('plan_id').primaryKey(),
  centerId: integer('center_id'),
  studentId: integer('student_id'),
  name: varchar('name', { length: 255 }),
  totalAmount: numeric('total_amount'),
  currency: varchar('currency', { length: 10 }),
  startDate: date('start_date'),
  endDate: date('end_date'),
  status: varchar('status', { length: 50 }),
  createdAt: timestamp('created_at'),
  updatedAt: timestamp('updated_at'),
});

const paymentPlanInstallments = pgTable('payment_plan_installments', {
  installmentId: serial('installment_id').primaryKey(),
  planId: integer('plan_id'),
  dueDate: date('due_date'),
  amount: numeric('amount'),
  status: varchar('status', { length: 50 }),
  createdAt: timestamp('created_at'),
  updatedAt: timestamp('updated_at'),
});

const payments = pgTable('payments', {
  paymentId: serial('payment_id').primaryKey(),
  studentId: integer('student_id'),
  centerId: integer('center_id'),
  paymentDate: date('payment_date'),
  amount: numeric('amount'),
  currency: varchar('currency', { length: 10 }),
  paymentMethod: varchar('payment_method', { length: 50 }),
  transactionReference: varchar('transaction_reference', { length: 255 }),
  receiptNumber: varchar('receipt_number', { length: 255 }),
  paymentStatus: varchar('payment_status', { length: 50 }),
  paymentType: varchar('payment_type', { length: 50 }),
  notes: text('notes'),
  discountId: integer('discount_id'),
  discountKind: varchar('discount_kind', { length: 40 }),
  discountValueType: varchar('discount_value_type', { length: 20 }),
  discountValue: numeric('discount_value'),
  originalAmount: numeric('original_amount'),
  discountAmount: numeric('discount_amount'),
  finalAmount: numeric('final_amount'),
  isComplete: boolean('is_complete'),
  transferSourceStudentId: integer('transfer_source_student_id'),
  transferTargetStudentId: integer('transfer_target_student_id'),
  transferSourceClassId: integer('transfer_source_class_id'),
  transferTargetClassId: integer('transfer_target_class_id'),
  transferEffectiveDate: date('transfer_effective_date'),
  coveredFrom: date('covered_from'),
  coveredTo: date('covered_to'),
  coverageDays: integer('coverage_days'),
  coverageTotalDays: integer('coverage_total_days'),
  deletedAt: timestamp('deleted_at'),
  createdAt: timestamp('created_at'),
  updatedAt: timestamp('updated_at'),
});

const refunds = pgTable('refunds', {
  refundId: serial('refund_id').primaryKey(),
  paymentId: integer('payment_id'),
  amount: numeric('amount'),
  reason: text('reason'),
  status: varchar('status', { length: 50 }),
  refundedAt: timestamp('refunded_at'),
  createdAt: timestamp('created_at'),
  updatedAt: timestamp('updated_at'),
});

const sessions = pgTable('sessions', {
  sessionId: serial('session_id').primaryKey(),
  centerId: integer('center_id'),
  classId: integer('class_id'),
  teacherId: integer('teacher_id'),
  sessionDate: date('session_date'),
  startTime: time('start_time'),
  durationMinutes: integer('duration_minutes'),
  endTime: time('end_time'),
  status: varchar('status', { length: 50 }),
  deletedAt: timestamp('deleted_at'),
  createdAt: timestamp('created_at'),
  updatedAt: timestamp('updated_at'),
});

const classSessions = pgTable('class_sessions', {
  sessionId: serial('session_id').primaryKey(),
  centerId: integer('center_id'),
  classId: integer('class_id'),
  teacherId: integer('teacher_id'),
  sessionDate: date('session_date'),
  startTime: time('start_time'),
  durationMinutes: integer('duration_minutes'),
  endTime: time('end_time'),
  status: varchar('status', { length: 50 }),
  createdAt: timestamp('created_at'),
  updatedAt: timestamp('updated_at'),
});

const subjects = pgTable('subjects', {
  subjectId: serial('subject_id').primaryKey(),
  centerId: integer('center_id'),
  classId: integer('class_id'),
  subjectName: varchar('subject_name', { length: 255 }),
  subjectCode: varchar('subject_code', { length: 100 }),
  teacherId: integer('teacher_id'),
  totalMarks: integer('total_marks'),
  passingMarks: integer('passing_marks'),
});

const superusers = pgTable('superusers', {
  superuserId: serial('superuser_id').primaryKey(),
  centerId: integer('center_id'),
  username: varchar('username', { length: 100 }),
  passwordHash: varchar('password_hash', { length: 255 }),
  firstName: varchar('first_name', { length: 100 }),
  lastName: varchar('last_name', { length: 100 }),
  email: varchar('email', { length: 255 }),
  role: varchar('role', { length: 50 }),
  status: varchar('status', { length: 50 }),
  isLocked: boolean('is_locked'),
  permissions: jsonb('permissions'),
  loginAttempts: integer('login_attempts'),
  canHardDelete: boolean('can_hard_delete'),
  lastLogin: timestamp('last_login'),
  createdAt: timestamp('created_at'),
  updatedAt: timestamp('updated_at'),
});

const telegramRegistrations = pgTable('telegram_registrations', {
  registrationId: serial('registration_id').primaryKey(),
  centerId: integer('center_id'),
  telegramUserId: varchar('telegram_user_id', { length: 100 }),
  status: varchar('status', { length: 50 }),
  payload: jsonb('payload'),
  createdAt: timestamp('created_at'),
  updatedAt: timestamp('updated_at'),
});

const telegramStudents = pgTable('telegram_students', {
  telegramStudentId: serial('telegram_student_id').primaryKey(),
  studentId: integer('student_id'),
  telegramUserId: varchar('telegram_user_id', { length: 100 }),
  createdAt: timestamp('created_at'),
  updatedAt: timestamp('updated_at'),
});

const telegramStudentRegistrations = pgTable('telegram_student_registrations', {
  registrationId: serial('registration_id').primaryKey(),
  telegramUserId: bigint('telegram_user_id', { mode: 'number' }).notNull(),
  telegramChatId: bigint('telegram_chat_id', { mode: 'number' }).notNull(),
  telegramUsername: varchar('telegram_username', { length: 100 }),
  firstName: varchar('first_name', { length: 100 }).notNull(),
  lastName: varchar('last_name', { length: 100 }).notNull(),
  phone: varchar('phone', { length: 30 }),
  dateOfBirth: date('date_of_birth'),
  parentName: varchar('parent_name', { length: 200 }),
  parentPhone: varchar('parent_phone', { length: 30 }),
  gender: varchar('gender', { length: 20 }),
  username: varchar('username', { length: 100 }),
  passwordHash: varchar('password_hash', { length: 255 }),
  schoolName: varchar('school_name', { length: 200 }),
  schoolClass: varchar('school_class', { length: 50 }),
  centerId: integer('center_id'),
  classLabel: varchar('class_label', { length: 100 }),
  status: varchar('status', { length: 30 }),
  convertedStudentId: integer('converted_student_id'),
  convertedAt: timestamp('converted_at'),
  createdAt: timestamp('created_at'),
  updatedAt: timestamp('updated_at'),
});

const tests = pgTable('tests', {
  testId: serial('test_id').primaryKey(),
  centerId: integer('center_id'),
  subjectId: integer('subject_id'),
  testName: varchar('test_name', { length: 255 }),
  testType: varchar('test_type', { length: 50 }),
  instructions: text('instructions'),
  totalMarks: integer('total_marks'),
  passingMarks: integer('passing_marks'),
  durationMinutes: integer('duration_minutes'),
  assignmentType: varchar('assignment_type', { length: 50 }),
  isTimed: boolean('is_timed'),
  shuffleQuestions: boolean('shuffle_questions'),
  showResultsImmediately: boolean('show_results_immediately'),
  allowRetake: boolean('allow_retake'),
  maxRetakes: integer('max_retakes'),
  testData: jsonb('test_data'),
  createdBy: integer('created_by'),
  createdByType: varchar('created_by_type', { length: 20 }),
  isActive: boolean('is_active'),
  isPrivate: boolean('is_private'),
  startDate: timestamp('start_date'),
  endDate: timestamp('end_date'),
  description: text('description'),
  createdAt: timestamp('created_at'),
  updatedAt: timestamp('updated_at'),
});

const testAssignments = pgTable('test_assignments', {
  assignmentId: serial('assignment_id').primaryKey(),
  centerId: integer('center_id'),
  testId: integer('test_id').notNull(),
  assignedToType: varchar('assigned_to_type', { length: 20 }).notNull(),
  assignedToId: integer('assigned_to_id').notNull(),
  assignedBy: integer('assigned_by').notNull(),
  assignedAt: timestamp('assigned_at'),
  dueDate: timestamp('due_date'),
  isMandatory: boolean('is_mandatory'),
  notes: text('notes'),
});

const readingPassages = pgTable('reading_passages', {
  passageId: serial('passage_id').primaryKey(),
  centerId: integer('center_id'),
  testId: integer('test_id').notNull(),
  title: varchar('title', { length: 255 }).notNull(),
  content: text('content').notNull(),
  wordCount: integer('word_count'),
  difficultyLevel: varchar('difficulty_level', { length: 20 }),
  passageOrder: integer('passage_order'),
  audioUrl: varchar('audio_url', { length: 500 }),
  imageUrl: varchar('image_url', { length: 500 }),
  createdAt: timestamp('created_at'),
});

const testQuestions = pgTable('test_questions', {
  questionId: serial('question_id').primaryKey(),
  centerId: integer('center_id'),
  testId: integer('test_id').notNull(),
  passageId: integer('passage_id'),
  questionText: text('question_text').notNull(),
  questionType: varchar('question_type', { length: 50 }).notNull(),
  marks: integer('marks'),
  negativeMarks: numeric('negative_marks'),
  questionOrder: integer('question_order'),
  options: jsonb('options'),
  correctAnswer: jsonb('correct_answer'),
  explanation: text('explanation'),
  imageUrl: varchar('image_url', { length: 500 }),
  isRequired: boolean('is_required'),
  wordLimit: integer('word_limit'),
  rubric: text('rubric'),
  createdAt: timestamp('created_at'),
});

const requestLogs = pgTable('request_logs', {
  logId: serial('log_id').primaryKey(),
  centerId: integer('center_id'),
  method: varchar('method', { length: 20 }),
  path: text('path'),
  statusCode: integer('status_code'),
  createdAt: timestamp('created_at'),
});

const testSubmissions = pgTable('test_submissions', {
  submissionId: serial('submission_id').primaryKey(),
  testId: integer('test_id'),
  studentId: integer('student_id'),
  centerId: integer('center_id'),
  startedAt: timestamp('started_at'),
  submittedAt: timestamp('submitted_at'),
  timeTakenSeconds: integer('time_taken_seconds'),
  submissionData: jsonb('submission_data'),
  totalScore: numeric('total_score'),
  obtainedMarks: numeric('obtained_marks'),
  percentage: numeric('percentage'),
  isPassed: boolean('is_passed'),
  feedback: text('feedback'),
  gradedBy: integer('graded_by'),
  gradedByType: varchar('graded_by_type', { length: 20 }),
  gradedAt: timestamp('graded_at'),
  attemptNumber: integer('attempt_number'),
  ipAddress: varchar('ip_address', { length: 50 }),
  status: varchar('status', { length: 50 }),
  createdAt: timestamp('created_at'),
  updatedAt: timestamp('updated_at'),
});

const testAnswers = pgTable('test_answers', {
  answerId: serial('answer_id').primaryKey(),
  centerId: integer('center_id'),
  submissionId: integer('submission_id').notNull(),
  questionId: integer('question_id').notNull(),
  studentAnswer: jsonb('student_answer'),
  isCorrect: boolean('is_correct'),
  marksObtained: numeric('marks_obtained'),
  feedback: text('feedback'),
  graded: boolean('graded'),
  gradedAt: timestamp('graded_at'),
  gradedBy: integer('graded_by'),
  gradedByType: varchar('graded_by_type', { length: 20 }),
});

const testResultsSummary = pgTable('test_results_summary', {
  resultId: serial('result_id').primaryKey(),
  centerId: integer('center_id'),
  testId: integer('test_id').notNull(),
  studentId: integer('student_id').notNull(),
  bestScore: numeric('best_score'),
  averageScore: numeric('average_score'),
  totalAttempts: integer('total_attempts'),
  lastAttemptAt: timestamp('last_attempt_at'),
  firstPassedAt: timestamp('first_passed_at'),
  isCompleted: boolean('is_completed'),
  certificateIssued: boolean('certificate_issued'),
  createdAt: timestamp('created_at'),
  updatedAt: timestamp('updated_at'),
});

const studentCoinTransactions = pgTable('student_coin_transactions', {
  transactionId: serial('transaction_id').primaryKey(),
  studentId: integer('student_id'),
  centerId: integer('center_id'),
  delta: integer('delta'),
  reason: text('reason'),
  createdBy: integer('created_by'),
  createdByType: varchar('created_by_type', { length: 50 }),
  sourceType: varchar('source_type', { length: 50 }),
  sourceId: integer('source_id'),
  createdAt: timestamp('created_at'),
  updatedAt: timestamp('updated_at'),
});

module.exports = {
  appSettings,
  translations,
  savedFilters,
  teacherTasks,
  teacherSalaries,
  teacherKpis,
  notifications,
  teacherPaymentCredentials,
  centers,
  rooms,
  physicalRooms,
  classes,
  teachers,
  students,
  studentAcquisitionSources,
  studentActionReasons,
  roomSlots,
  roomBookings,
  assignments,
  attendance,
  auditLogs,
  debts,
  discounts,
  grades,
  importJobs,
  invoices,
  invoiceItems,
  owners,
  parents,
  parentStudents,
  paymentPlans,
  paymentPlanInstallments,
  payments,
  refunds,
  sessions,
  classSessions,
  subjects,
  superusers,
  telegramRegistrations,
  telegramStudents,
  telegramStudentRegistrations,
  tests,
  testAssignments,
  readingPassages,
  testQuestions,
  testSubmissions,
  testAnswers,
  testResultsSummary,
  requestLogs,
  studentCoinTransactions,
};

export {};
